package co.com.soinsoftware.hotelero.view;

import co.com.soinsoftware.hotelero.controller.MenuController;
import javax.swing.JMenuBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Carlos Rodriguez
 * @since 17/07/2016
 * @version 1.0
 */
public class JFRoom extends javax.swing.JFrame {
    
    /**
     * Creates new form RegistrarUsuario
     */
    public JFRoom() {
        this.initComponents();
    }
    
    public void addController(final MenuController controller) {
        final JMenuBar menuBar = new JMBAppMenu(controller);
        this.setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpClient = new javax.swing.JPanel();
        jlbIdentification = new javax.swing.JLabel();
        jtfIdentification = new javax.swing.JFormattedTextField();
        jlbName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JFormattedTextField();
        jlbCareer = new javax.swing.JLabel();
        jtfCareer = new javax.swing.JTextField();
        jlbSiteFrom = new javax.swing.JLabel();
        jtfSiteFrom = new javax.swing.JTextField();
        jlbSiteTo = new javax.swing.JLabel();
        jtfSiteTo = new javax.swing.JTextField();
        jlbInitialDate = new javax.swing.JLabel();
        jdcInitialDate = new com.toedter.calendar.JDateChooser();
        jlbInitialHour = new javax.swing.JLabel();
        jtfIdentification1 = new javax.swing.JFormattedTextField();
        jpTitle = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jpFirstFloor = new javax.swing.JPanel();
        jbt101 = new javax.swing.JButton();
        jbt102 = new javax.swing.JButton();
        jbt103 = new javax.swing.JButton();
        jbt104 = new javax.swing.JButton();
        jbt105 = new javax.swing.JButton();
        jbt106 = new javax.swing.JButton();
        jbt107 = new javax.swing.JButton();
        jpSecondFloor = new javax.swing.JPanel();
        jbt201 = new javax.swing.JButton();
        jbt202 = new javax.swing.JButton();
        jbt203 = new javax.swing.JButton();
        jbt204 = new javax.swing.JButton();
        jbt205 = new javax.swing.JButton();
        jbt206 = new javax.swing.JButton();
        jbt207 = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        jpAction = new javax.swing.JPanel();
        jbtBook = new javax.swing.JButton();
        jbtCheckIn = new javax.swing.JButton();
        jbtClean = new javax.swing.JButton();
        jpReservationList = new javax.swing.JPanel();
        jspReservationList = new javax.swing.JScrollPane();
        jtbReservationList = new javax.swing.JTable();
        jpColorDesc = new javax.swing.JPanel();
        jbtWhite = new javax.swing.JButton();
        jbtGreen = new javax.swing.JButton();
        jbtRed = new javax.swing.JButton();
        jbtYellow = new javax.swing.JButton();
        jlbColorDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotelero");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1050, 690));

        jpClient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        jlbIdentification.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbIdentification.setText("Cedula(*):");

        jtfIdentification.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jtfIdentification.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jlbName.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbName.setText("Nombre(*):");

        jtfName.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel6.setText("Teléfono(*):");

        jtfPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jtfPhone.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jlbCareer.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbCareer.setText("Profesión:");

        jtfCareer.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jlbSiteFrom.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbSiteFrom.setText("Procedencia:");

        jtfSiteFrom.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jlbSiteTo.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbSiteTo.setText("Destino:");

        jtfSiteTo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jlbInitialDate.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbInitialDate.setText("Fecha de llegada(*):");

        jdcInitialDate.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jlbInitialHour.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbInitialHour.setText("Hora de llegada:");

        jtfIdentification1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jtfIdentification1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        javax.swing.GroupLayout jpClientLayout = new javax.swing.GroupLayout(jpClient);
        jpClient.setLayout(jpClientLayout);
        jpClientLayout.setHorizontalGroup(
            jpClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClientLayout.createSequentialGroup()
                        .addGroup(jpClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfCareer)
                            .addComponent(jlbCareer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbIdentification, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfIdentification)
                            .addComponent(jlbName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfName)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPhone)
                            .addComponent(jlbSiteFrom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSiteFrom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbSiteTo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSiteTo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbInitialDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcInitialDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jlbInitialHour, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtfIdentification1))
                .addContainerGap())
        );
        jpClientLayout.setVerticalGroup(
            jpClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbIdentification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbCareer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbSiteFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSiteFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbSiteTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSiteTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbInitialDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcInitialDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbInitialHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfIdentification1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTitle.setBackground(new java.awt.Color(255, 255, 255));

        jlbTitle.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlbTitle.setText("Habitaciones (Check-in, Reservar)");

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jlbTitle)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jpFirstFloor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primer Piso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        jbt101.setBackground(new java.awt.Color(255, 255, 255));
        jbt101.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt101.setText("101");
        jbt101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt101ActionPerformed(evt);
            }
        });

        jbt102.setBackground(new java.awt.Color(255, 255, 255));
        jbt102.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt102.setText("102");
        jbt102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt102ActionPerformed(evt);
            }
        });

        jbt103.setBackground(new java.awt.Color(255, 255, 255));
        jbt103.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt103.setText("103");
        jbt103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt103ActionPerformed(evt);
            }
        });

        jbt104.setBackground(new java.awt.Color(255, 255, 255));
        jbt104.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt104.setText("104");
        jbt104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt104ActionPerformed(evt);
            }
        });

        jbt105.setBackground(new java.awt.Color(255, 255, 255));
        jbt105.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt105.setText("105");
        jbt105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt105ActionPerformed(evt);
            }
        });

        jbt106.setBackground(new java.awt.Color(255, 255, 255));
        jbt106.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt106.setText("106");
        jbt106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt106ActionPerformed(evt);
            }
        });

        jbt107.setBackground(new java.awt.Color(255, 255, 255));
        jbt107.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt107.setText("107");
        jbt107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt107ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFirstFloorLayout = new javax.swing.GroupLayout(jpFirstFloor);
        jpFirstFloor.setLayout(jpFirstFloorLayout);
        jpFirstFloorLayout.setHorizontalGroup(
            jpFirstFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFirstFloorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFirstFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFirstFloorLayout.createSequentialGroup()
                        .addComponent(jbt101, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt102, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt103, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt104, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFirstFloorLayout.createSequentialGroup()
                        .addComponent(jbt105, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt106, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt107, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFirstFloorLayout.setVerticalGroup(
            jpFirstFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFirstFloorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFirstFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt101, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt102, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt103, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt104, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFirstFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt105, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt107, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSecondFloor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segundo Piso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        jbt201.setBackground(new java.awt.Color(255, 255, 255));
        jbt201.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt201.setText("201");
        jbt201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt201ActionPerformed(evt);
            }
        });

        jbt202.setBackground(new java.awt.Color(255, 255, 255));
        jbt202.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt202.setText("202");
        jbt202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt202ActionPerformed(evt);
            }
        });

        jbt203.setBackground(new java.awt.Color(255, 255, 255));
        jbt203.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt203.setText("203");
        jbt203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt203ActionPerformed(evt);
            }
        });

        jbt204.setBackground(new java.awt.Color(255, 255, 255));
        jbt204.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt204.setText("204");
        jbt204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt204ActionPerformed(evt);
            }
        });

        jbt205.setBackground(new java.awt.Color(255, 255, 255));
        jbt205.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt205.setText("205");
        jbt205.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt205ActionPerformed(evt);
            }
        });

        jbt206.setBackground(new java.awt.Color(255, 255, 255));
        jbt206.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt206.setText("206");
        jbt206.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt206ActionPerformed(evt);
            }
        });

        jbt207.setBackground(new java.awt.Color(255, 255, 255));
        jbt207.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbt207.setText("207");
        jbt207.setPreferredSize(new java.awt.Dimension(89, 23));
        jbt207.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt207ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSecondFloorLayout = new javax.swing.GroupLayout(jpSecondFloor);
        jpSecondFloor.setLayout(jpSecondFloorLayout);
        jpSecondFloorLayout.setHorizontalGroup(
            jpSecondFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSecondFloorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSecondFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpSecondFloorLayout.createSequentialGroup()
                        .addComponent(jbt201, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt202, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt203, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSecondFloorLayout.createSequentialGroup()
                        .addComponent(jbt205, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt206, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt207, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt204, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSecondFloorLayout.setVerticalGroup(
            jpSecondFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSecondFloorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSecondFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt201, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt202, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt203, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt204, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSecondFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpSecondFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbt205, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbt206, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbt207, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soin.png"))); // NOI18N

        jpAction.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        jbtBook.setBackground(new java.awt.Color(16, 135, 221));
        jbtBook.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jbtBook.setForeground(new java.awt.Color(255, 255, 255));
        jbtBook.setText("Reservar");
        jbtBook.setPreferredSize(new java.awt.Dimension(89, 23));

        jbtCheckIn.setBackground(new java.awt.Color(16, 135, 221));
        jbtCheckIn.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jbtCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        jbtCheckIn.setText("Check-In");
        jbtCheckIn.setPreferredSize(new java.awt.Dimension(89, 23));

        jbtClean.setBackground(new java.awt.Color(16, 135, 221));
        jbtClean.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jbtClean.setForeground(new java.awt.Color(255, 255, 255));
        jbtClean.setText("Limpiar");
        jbtClean.setPreferredSize(new java.awt.Dimension(89, 23));

        javax.swing.GroupLayout jpActionLayout = new javax.swing.GroupLayout(jpAction);
        jpAction.setLayout(jpActionLayout);
        jpActionLayout.setHorizontalGroup(
            jpActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jpActionLayout.setVerticalGroup(
            jpActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpReservationList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proximas reservas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        jtbReservationList.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jtbReservationList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspReservationList.setViewportView(jtbReservationList);

        javax.swing.GroupLayout jpReservationListLayout = new javax.swing.GroupLayout(jpReservationList);
        jpReservationList.setLayout(jpReservationListLayout);
        jpReservationListLayout.setHorizontalGroup(
            jpReservationListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspReservationList, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jpReservationListLayout.setVerticalGroup(
            jpReservationListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservationListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspReservationList))
        );

        jpColorDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción de colores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        jbtWhite.setBackground(new java.awt.Color(255, 255, 255));
        jbtWhite.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbtWhite.setText("Habitaciones disponibles");

        jbtGreen.setBackground(java.awt.Color.green);
        jbtGreen.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbtGreen.setText("Habitación seleccionada");

        jbtRed.setBackground(java.awt.Color.red);
        jbtRed.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbtRed.setText("Habitaciones ocupadas");

        jbtYellow.setBackground(java.awt.Color.yellow);
        jbtYellow.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jbtYellow.setText("Habitaciones reservadas");

        jlbColorDesc.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jlbColorDesc.setText("Los colores indican el estado de la habitación según la fecha de llegada");

        javax.swing.GroupLayout jpColorDescLayout = new javax.swing.GroupLayout(jpColorDesc);
        jpColorDesc.setLayout(jpColorDescLayout);
        jpColorDescLayout.setHorizontalGroup(
            jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpColorDescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpColorDescLayout.createSequentialGroup()
                        .addGroup(jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtYellow, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jbtWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtGreen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jbtRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jlbColorDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpColorDescLayout.setVerticalGroup(
            jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpColorDescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbColorDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtWhite)
                    .addComponent(jbtGreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpColorDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtRed)
                    .addComponent(jbtYellow))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpColorDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpFirstFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpSecondFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jpReservationList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpReservationList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpColorDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpFirstFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSecondFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jpAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt101ActionPerformed

    private void jbt102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt102ActionPerformed

    private void jbt103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt103ActionPerformed

    private void jbt104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt104ActionPerformed

    private void jbt105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt105ActionPerformed

    private void jbt106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt106ActionPerformed

    private void jbt107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt107ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt107ActionPerformed

    private void jbt201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt201ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt201ActionPerformed

    private void jbt202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt202ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt202ActionPerformed

    private void jbt203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt203ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt203ActionPerformed

    private void jbt204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt204ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt204ActionPerformed

    private void jbt205ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt205ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt205ActionPerformed

    private void jbt206ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt206ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt206ActionPerformed

    private void jbt207ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt207ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt207ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbt101;
    private javax.swing.JButton jbt102;
    private javax.swing.JButton jbt103;
    private javax.swing.JButton jbt104;
    private javax.swing.JButton jbt105;
    private javax.swing.JButton jbt106;
    private javax.swing.JButton jbt107;
    private javax.swing.JButton jbt201;
    private javax.swing.JButton jbt202;
    private javax.swing.JButton jbt203;
    private javax.swing.JButton jbt204;
    private javax.swing.JButton jbt205;
    private javax.swing.JButton jbt206;
    private javax.swing.JButton jbt207;
    private javax.swing.JButton jbtBook;
    private javax.swing.JButton jbtCheckIn;
    private javax.swing.JButton jbtClean;
    private javax.swing.JButton jbtGreen;
    private javax.swing.JButton jbtRed;
    private javax.swing.JButton jbtWhite;
    private javax.swing.JButton jbtYellow;
    private com.toedter.calendar.JDateChooser jdcInitialDate;
    private javax.swing.JLabel jlbCareer;
    private javax.swing.JLabel jlbColorDesc;
    private javax.swing.JLabel jlbIdentification;
    private javax.swing.JLabel jlbInitialDate;
    private javax.swing.JLabel jlbInitialHour;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbSiteFrom;
    private javax.swing.JLabel jlbSiteTo;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jpAction;
    private javax.swing.JPanel jpClient;
    private javax.swing.JPanel jpColorDesc;
    private javax.swing.JPanel jpFirstFloor;
    private javax.swing.JPanel jpReservationList;
    private javax.swing.JPanel jpSecondFloor;
    private javax.swing.JPanel jpTitle;
    private javax.swing.JScrollPane jspReservationList;
    private javax.swing.JTable jtbReservationList;
    private javax.swing.JTextField jtfCareer;
    private javax.swing.JFormattedTextField jtfIdentification;
    private javax.swing.JFormattedTextField jtfIdentification1;
    private javax.swing.JTextField jtfName;
    private javax.swing.JFormattedTextField jtfPhone;
    private javax.swing.JTextField jtfSiteFrom;
    private javax.swing.JTextField jtfSiteTo;
    private javax.swing.JLabel lbImage;
    // End of variables declaration//GEN-END:variables
}
